@startuml Simplified-Smart-Lock
class User {
  +String email
  +String password
  +void register(email: String, password: String)
  +boolean authenticate(password: String)
  +boolean signout(password: String)
}

class SmartLock {
  +String smartLockId
  +String userId
  +boolean lockStatus
  +void lock(): void
  +boolean unlock(fingerprintImage: String): boolean
  +boolean getLockStatus(): boolean // true if locked, false if unlocked
}

class Sensor {
  +String sensorId
  +String type // [temperature, humidity, light]
  +String value
  +DateTime timestamp
  +void createData(sensorId: String, value: String)
  +String getData(): String
}

class Log {
  +String logId
  +String fingerprintId
  +String faceImage
  +String status
  +DateTime timestamp
  +void createLog(fingerprintId: String, status: String, faceImage: String)
  +String[] getLogs(): String[]
  +String getLog(logId: String): String
}

class Fingerprint {
  +String fingerprintId
  +String name
  +String fingerprintImage
  +String smartLockId // foreign key
  +void createFingerprint(name: String, fingerprintImage: String)
  +void updateFingerprint(fingerprintId: String, name: String, fingerprintImage: String)
  +void deleteFingerprint(fingerprintId: String)
  +String[] getFingerprints(): String[]
}

User "1..1" -- "1..1" SmartLock : owns >
SmartLock "1" -- "0..*" Log : creates >
SmartLock "1" -- "0..*" Sensor : contains >
Fingerprint "1" -- "0..*" Log : logs >
@enduml
